### ISSUE TITLE
Please update compiler to 1.28 (or 1.29, or 1.30 etc)

### ISSUE THREAD

**Issue by diwic** [rust-lang-nursery/docs.rs#233]
Hello,

It seems like docs for my crate failed to build with [this error](https://docs.rs/crate/reffers/0.5.0/builds/115733):

    error[E0658]: use of unstable library feature 'allocator_api' (see issue #32838)

It builds fine with 1.28 stable, so I'm guessing that the compiler needs updating? 

Thanks for an awesome service anyhow :-)

**Comment by Thomasdezeeuw** [comment]
Or to 1.29 which was just released. @onur is there anyway we can help with this?

**Comment by katyo** [comment]
Or to nightly 1.30

**Comment by diwic** [comment]
As this issue has been lingering for a month without a reply (except for others also affected by the same issue), I've tried raising it here: https://internals.rust-lang.org/t/whats-the-state-of-docs-rs/8535

**Comment by dekellum** [comment]
Recent docs.rs failures, as well as the failure linked at top of this issues, show versions as follows:

https://docs.rs/crate/futures-preview/0.3.0-alpha.8/builds/121935
> $ rustc --version
> rustc 1.28.0-dev (b9bf4f162 2018-06-02)
> $ cratesfyi --version
> cratesfyi 0.5.0 (579f83b 2018-03-05)

Where the rustc sha matches the merge: onur/rust@b9bf4f162.
Which has rust-lang/rust@edae1cc3 as the rust-side parent being merged. 

So rustc 1.28.0-nightly (4ecf12bf0 2018-06-02) is a close approximation which can still be installed with rustup (e.g. `rustup install nightly-2018-06-03`) to test `cargo doc` behavior.  Note this is 2 months before a stable channel 1.28 was released.

**Comment by jonhoo** [comment]
Work is ongoing on this front now, but will take some time. https://github.com/onur/docs.rs/pull/243 is a start. You can see unofficial in-development progress (very much beta) at http://docsrs.csail.mit.edu/.

**Comment by QuietMisdreavus** [comment]
Now that https://github.com/rust-lang-nursery/docs.rs/pull/243 is merged, docs.rs is using `1.31.0-nightly (78ff609d7 2018-10-19)` as its rustc/rustdoc version.

**Comment by CryZe** [comment]
Will failed builds be requeued or do we have to publish new versions? @QuietMisdreavus

**Comment by QuietMisdreavus** [comment]
Most failed builds have been rebuilt. If you find something that hasn't been rebuilt this week, please report it into the "missing crates" issue (https://github.com/rust-lang-nursery/docs.rs/issues/23) so we can look into it.
